[[chapter-controls]]
== Controls

Apache Click provides a rich set of Controls which support client side
rendering and server side processing. Please see the
link:../../click-api/org/apache/click/control/package-summary.html[Javadoc],
which provides extensive information and examples of the core Controls.

This chapter covers Control in detail including the Control life cycle,
Control listeners and localization.

=== Control Interface

Controls provide the server side components that process user input, and
render their display to the user. Controls are equivalent to Visual
Basic Controls or Delphi Components.

Controls handle the processing of user input in the
link:../../click-api/org/apache/click/Control.html#onProcess()[onProcess]
method and render their HTML display using the toString() method. The
execution sequence for a Control being processed and rendered is
illustrated in the figure below.

In Click all control classes must implement the
link:../../click-api/org/apache/click/Control.html[Control] interface.
The Control interface is depicted in the figure below.

Methods on the Control interface include:

* link:../../click-api/org/apache/click/Control.html#getHeadElements()[getHeadElements()]
- defines the controls HTML header imports.
* link:../../click-api/org/apache/click/Control.html#getMessages()[getMessages()]
- defines the controls localized messages map.
* link:../../click-api/org/apache/click/Control.html#getName()[getName()]
/
link:../../click-api/org/apache/click/Control.html#setName(java.lang.String)[setName()]
  -   defines the controls name in the Page model or Form fields.
* link:../../click-api/org/apache/click/Control.html#getParent()[getParent()]
/
link:../../click-api/org/apache/click/Control.html#setParent(java.lang.Object)[setParent()]
  -   defines the controls parent.
* link:../../click-api/org/apache/click/Control.html#onDeploy(javax.servlet.ServletContext)[onDeploy()]
- deploy resources on startup.
* link:../../click-api/org/apache/click/Control.html#onInit()[onInit()]
- on initialize event handler.
* link:../../click-api/org/apache/click/Control.html#onProcess()[onProcess()]
- process request event handler.
* link:../../click-api/org/apache/click/Control.html#onDestroy()[onDestroy()]
- on destroy event handler.
* link:../../click-api/org/apache/click/Control.html#render(org.apache.click.util.HtmlStringBuffer)[render()]
- generate the control's HTML representation.

=== Control Listener

Click Controls provide an action listener mechanism similar to a
`+java.awt.ActionListener+`.

Click supports two styles of action listeners. The first is using the
link:../../click-api/org/apache/click/ActionListener.html[ActionListener]
interface and
link:../../click-api/org/apache/click/control/AbstractControl.html#setActionListener(org.apache.click.ActionListener)[setActionListener(ActionListener)]
method which provides compile time safety.

The second is to register the action listener via the
link:../../click-api/org/apache/click/Control.html#setListener(java.lang.Object, java.lang.String)[setListener(Object&#44;
String)] method where you specify the call back method via its name.
This second style uses less lines of code, but has no compile time
safety.

Examples of these two action listener styles are provided below:

[source,java]
----
public class ActionDemo extends BorderPage {

    // Uses listener style 1
    public ActionLink link = new ActionLink();

    // Uses listener style 2
    public ActionButton button = new ActionButton();

    public ActionDemo() {

        // Verbose but provides compile time safety
        link.setActionListener(new ActionListener() {
            public boolean onAction(Control source) {
                return onLinkClick(source);
            }
        });

        // Succinct but typos will cause runtime errors
        button.setListener(this, "onButtonClick");
    }

    // Event Handlers ---------------------------------------------------------

    public boolean onLinkClick(Control source) {
        ..
        return true;
    }

    public boolean onButtonClick() {
        ..
        return true;
    }
}
----

All call back listener methods must return a boolean value. If they
return true the further processing of other controls and page methods
should continue. Otherwise if they return false, then any further
processing should be aborted. By returning false you can effectively
exit at this point and redirect or forward to another page. This
execution logic is illustrated in the link:#activity-diagram[Page
Execution Activity Diagram].

Being able to stop further processing and do something else can be very
handy. For example your Pages onRender() method may perform an expensive
database operation. By returning false in an event handler you can skip
this step and render the template or forward to the next page.

[[control-class]]
=== Control Classes

Core control classes are defined in the package
link:../../click-api/org/apache/click/control/package-summary.html[org.apache.click.control].
This package includes controls for the essential HTML elements.

Extended control classes are provided in the Click Extras package
link:../../extras-api/org/apache/click/extras/control/package-summary.html[org.apache.click.extras.control].
Click Extras classes can contain dependencies to 3rd party frameworks.

A subset of these control classes are depicted in the figure below.

The key control classes include:

* link:../../click-api/org/apache/click/control/ActionLink.html[ActionLink]
- provides an anchor link that can invoke action listeners.
* link:../../click-api/org/apache/click/control/Field.html[Field] -
provides the abstract form field control.
* link:../../click-api/org/apache/click/control/Form.html[Form] -
provides a form control for processing, validation and rendering.
* link:../../click-api/org/apache/click/control/Submit.html[Submit] -
provides an input type submit control that can invoke action listeners.
* link:../../click-api/org/apache/click/control/TextField.html[TextField]
- provides an input type text control that can invoke action listeners.

The control classes are designed to support subclassing for customized
behaviour. All control fields have protected visibility and have public
accessor methods.

You can also aggregate controls to build more complex controls. For
example the
link:../../extras-api/org/apache/click/extras/control/CreditCardField.html[CreditCardField]
uses a link:../../click-api/org/apache/click/control/Select.html[Select]
control to render the different credit card types.

[[control-message-properties]]
=== Message Properties

Control strings for field validation messages and HTML formatting
strings are externalized in the properties file. By using these
properties files you can localize a Click application for your
particular language and dialect.

==== Message Resolution

Messages are looked up in a particular order enabling taylor specific
messages, for your controls, individual pages or across your entire
application. The order in which localized messages are resolved is:

*Page scope messages*::
  Message lookups are first resolved to the Page classes message bundle
  if it exists. For example a `+Login+` page may define the message
  properties:
  +
....
/com/mycorp/page/Login.properties
....
  +
  If you want to tailor messages for a particular page this is where to
  place them.
*Global page scope messages*::
  Next message lookups are resolved to the global pages message bundle
  if it exists.
  +
....
/click-page.properties
....
  +
  If you want messages to be used across your entire application this is
  where to place them.
*Control scope messages*::
  Next message lookups are resolved to the Control classes message
  bundle if it exists. For example a `+CustomTextField+` control may
  define the message properties:
  +
....
/com/mycorp/control/CustomTextField.properties
....
  +
  A custom control's messages can be placed here (or the global control
  scope covered next) and overridden by one of the above options.
*Global control scope messages*::
  Finally message lookups are resolved to the global application control
  message bundle if the message has not already been found. The global
  control properties file is:
  +
....
/click-control.properties
....
  +
  Control messages can be placed here and overridden by one of the above
  options.

==== Control Properties

To customize the `+click-control.properties+` simply add this file to
your classpath and tailor the specific values.

Note when customizing the message properties you must include all the
properties, not just the ones you want to override.

....
# Click Control messages
field-maxlength-error={0} must be no longer than {1} characters
field-minlength-error={0} must be at least {1} characters
field-required-error=You must enter a value for {0}

file-required-error=You must enter a filename for {0}

label-required-prefix=
label-required-suffix=<span class="required">*</span>
label-not-required-prefix=
label-not-required-suffix=&nbsp;

not-checked-error=You must select {0}

number-maxvalue-error={0} must not be larger than {1}
number-minvalue-error={0} must not be smaller than {1}

select-error=You must select a value for {0}

table-first-label=First
table-first-title=Go to first page
table-previous-label=Prev
table-previous-title=Go to previous page
table-next-label=Next
table-next-title=Go to next page
table-last-label=Last
table-last-title=Go to last page
table-goto-title=Go to page
table-page-banner=<span class="pagebanner">{0} items found, displaying {1} to {2}.</span>
table-page-banner-nolinks=
  <span class="pagebanner-nolinks">{0} items found, displaying {1} to {2}.</span>
table-page-links=<span class="pagelinks">[{0}/{1}] {2} [{3}/{4}]</span>
table-page-links-nobanner=<span class="pagelinks-nobanner">[{0}/{1}] {2} [{3}/{4}]</span>
table-no-rows-found=No records found.

table-inline-first-image=/click/paging-first.gif
table-inline-first-disabled-image=/click/paging-first-disabled.gif
table-inline-previous-image=/click/paging-prev.gif
table-inline-previous-disabled-image=/click/paging-prev-disabled.gif
table-inline-next-image=/click/paging-next.gif
table-inline-next-disabled-image=/click/paging-next-disabled.gif
table-inline-last-image=/click/paging-last.gif
table-inline-last-disabled-image=/click/paging-last-disabled.gif
table-inline-page-links=Page   {0} {1} {2} {3} {4}

# Message displayed when a error occurs when the application is in "production" mode
production-error-message=
  <div id='errorReport' class='errorReport'>The application encountered an unexpected error.
  </div>
      
....

==== Accessing Messages

Controls support a hierarchy of resource bundles for displaying
validation error messages and display messages. These localized messages
can be accessed through the AbstractControl methods:

* link:../../click-api/org/apache/click/control/AbstractControl.html#getMessage(java.lang.String)[getMessage(String)]
* link:../../click-api/org/apache/click/control/AbstractControl.html#getMessage(java.lang.String,%20java.lang.Object...)[getMessage(String&#44;
Object...)]
* link:../../click-api/org/apache/click/control/AbstractControl.html#getMessages()[getMessages()]
* link:../../click-api/org/apache/click/control/Field.html#setErrorMessage(java.lang.String)[setErrorMessage(String)]
- this method is defined on the Field class
* link:../../click-api/org/apache/click/control/Field.html#setErrorMessage(java.lang.String,%20java.lang.Object)[setErrorMessage(String&#44;
Object)] - this method is defined on the Field class

These methods use the `+Locale+` of the request to lookup the string
resource bundle, and use `+MessageFormat+` for any string formatting.

=== Control HEAD Elements

The Control interface provides the method
link:../../click-api/org/apache/click/Control.html#getHeadElements()[getHeadElements()]
which allows the Control to add Page HEAD
link:../../click-api/org/apache/click/element/Element.html[elements]
such as
link:../../click-api/org/apache/click/element/JsImport.html[JsImport],
link:../../click-api/org/apache/click/element/JsScript.html[JsScript],
link:../../click-api/org/apache/click/element/CssImport.html[CssImport]
and
link:../../click-api/org/apache/click/element/CssStyle.html[CssStyle].

Here is an example of adding HEAD elements to a custom `+Control+`:

[source,java]
----
public class MyControl extends AbstractControl {

    public MyControl() {

        /**
         * Override the default getHeadElements implementation to return
         * MyControl's list of HEAD elements.
         *
         * Note that the variable headElements is defined in AbstractControl.
         *
         * @return list the list of HEAD elements
         */
        public List getHeadElements() {

            // Use lazy loading to only add the HEAD elements once and when needed.
            if (headElements == null) {

                // Get the head elements from the super implementation
                headElements = super.getHeadElements();

                // Add the JavaScript import "/mycontrol.js" to the control
                headElements.add(new JsImport("/mycontrol.js"));

                // Add the Css import "/mycontrol.css" to the control
                headElements.add(new CssImport("/mycontrol.css"));
            }
            return headElements;
        }
    }

    ...

} 
----

In the example above we added the HEAD elements by overriding the
Control's getHeadElements method, however you can add HEAD elements from
anywhere in the Control including the event handlers `+onInit+`,
`+onGet+`, `+onPost+`, `+onRender+` etc. Please see
link:../../click-api/org/apache/click/Page.html#getHeadElements()[getHeadElements()]
for more details.

`+MyControl+` will add the following HEAD elements to the Page HEAD
section, together with HEAD elements added by the Page and other
controls (assume the application context is "/myapp"):

[source,xml]
----
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="/myapp/mycontrol.css"></link>
  </head>

  <body>

    ...

    <script type="text/javascript" src="/myapp/mycontrol.js"/>

  </body>
</html> 
----

A live demo showing how to add HEAD elements from a custom Control can
be seen
http://click.avoka.com/click-examples/general/control-head-demo.htm[here].

=== Container

link:../../click-api/org/apache/click/control/Container.html[Container]
is a Control that can contain other Controls, thus forming a hierarchy
of components. Container enables components to add, remove and retrieve
other controls. Listed below are example Containers:

* link:../../click-api/org/apache/click/control/Form.html[Form] - an
HTML form which provides default layout of fields and error feedback.
* link:../../click-api/org/apache/click/control/Panel.html[Panel] -
similar to link:../../click-api/org/apache/click/Page.html[Page], this
Container provides its own template and model.
* link:../../click-api/org/apache/click/control/FieldSet.html[FieldSet]
- draws a legend (border) around its child Controls.

These Containers are depicted in the figure below.

The following classes provides convenient extension points for creating
custom Containers:

* link:../../click-api/org/apache/click/control/AbstractContainer.html[AbstractContainer]
* link:../../extras-api/org/apache/click/extras/control/AbstractContainerField.html[AbstractContainerField]

Lets cover each of them here.

==== AbstractContainer

Enables easy creation of custom Containers, for example an html _div_ or
_span_ element:

[source,java]
----
public class Div extends AbstractContainer {

    public Div(String name) {
        super(name);
    }

    public String getTag() {
        // Return the control's HTML tag.
        return "div";
    }
}
----

Lets try out the newly created `+Container+` above: (note the
`+MockContext+` used in this test is described in the
link:../../mock-api/overview-summary.html[Mock Test Support]
documentation)

[source,java]
----
public class Test {
    public static void main (String args[]) {
        // Create mock context in which to test the container.
        MockContext.initContext();

        // Create a div instance called "mydiv"
        String containerName = "mydiv";
        Div mydiv = new Div(containerName);

        // Add a control to the container
        mydiv.add(new TextField("myfield"));

        System.out.println(mydiv);
    }
}
----

Executing the above example results in the following output:

[source,xml]
----
<div name="mydiv" id="mydiv">
    <input type="text" name="myfield" id="myfield" value="" size="20" />
</div>
----

==== AbstractContainerField

AbstractContainerField extends Field and implements the Container
interface. This provides a convenient base class in case you run into a
situation where you need both a Field and Container.

Below is an example of how AbstractContainerField might be used:

[source,java]
----
public class FieldAndContainer extends AbstractContainerField {

    public FieldAndContainer(String name) {
        super(name);
    }

    // Return the html tag to render
    public String getTag() {
        return "div";
    }
}
----

To test the new class we use the following snippet:

[source,java]
----
public class Test {
    public static void main (String args[]) {
        // Create mock context in which to test the container.
        MockContext.initContext();

        // Create a FieldContainer instance called "field_container"
        String containerName = "field_container";
        FieldAndContainer fieldAndContainer = new FieldAndContainer(containerName);

        // Add a couple of fields to the container
        fieldAndContainer.add(new TextField("myfield"));
        fieldAndContainer.add(new TextArea("myarea"));

        System.out.println(fieldAndContainer);
    }
}
----

Executing the snippet produces the output:

[source,xml]
----
<div name="field_container" id="field_container">
    <input type="text" name="myfield" id="myfield" value="" size="20"/>
    <textarea name="myarea" id="myarea" rows="3" cols="20"></textarea>
</div>
----

[[layout]]
=== Layouts

Controls such as
link:../../click-api/org/apache/click/control/Form.html[Form] takes care
of layout and error reporting automatically, and for many use cases the
auto-layout approach is good enough. It is certainly very productive.

However for custom or complex layouts, auto-layout is not always the
best choice. There are two approaches for creating custom layouts.

* Template approach - use a template engine such as Velocity, Freemarker
or JSP to declare the layout as HTML markup.
* Programmatic approach - build custom layout components using Java.
This option is very similar to building components using Swing.

==== Template layout

The
link:../../click-api/org/apache/click/control/Form.html#manual-layout[Template]
approach separates the Page and layout logic. The Page is used to
implement the presentation logic such as creating controls, registering
listeners and copying data to domain objects, while the template is used
to layout the Page controls.

Lets walk through an example using the template approach. Below we
create an EmployeePage which contains a Form and a bunch of fields and
submit button.

[source,java]
----
// EmployeePage.java
public EmployeePage extends Page {

    private Form form;

    public void onInit() {
        // Create form
        Form form = new Form("form");

        // Add a couple of fields to the form
        form.add(new TextField("firstname"));
        form.add(new TextField("lastname"));
        form.add(new IntegerField("age"));
        form.add(new DoubleField("salary"));

        // Add a submit button to form
        form.add(new Submit("add", "Add Employee"));

        // Add form the page
        addControl(form);
    }
}
----

Lets imagine we want to create a layout using the HTML tags, <div> and
<ol>.

We would then provide the markup for the `+employee.htm+` template as
shown below, using a template engine such as Velocity:

[source,xml]
----
<!-- employee.htm -->
${form.startTag()}
    <div style="margin: 1em;">
        <ol>
            <li>
                <label for="firstname">Firstname:</label>
                ${form.fields.firstname}
            </li>
            <li>
                <label for="lastname">Lastname:</label>
                ${form.fields.lastname}
            </li>
            <li>
                <label for="age">Age:</label>
                ${form.fields.age}
            </li>
            <li>
                <label for="salary">Salary:</label>
                ${form.fields.salary}
            </li>
        </ol>
    </div>
    ${form.fields.submit}
${form.endTag()}
----

Using CSS the markup above can further be styled and transformed into a
nice looking form.

There are pros and cons to using the template approach.

One of the advantages is that the layout is explicit and one can easily
tweak it if needed. For example instead of using divs and ordered lists,
one can change the template to leverage a table layout.

A disadvantage is added redundancy. In the example above we created the
fields in Java, and laid them out using markup in the template. If the
requirements should change to add a new field for example, one will have
to add the field in the Page as well as the template.

However it is possible to "generify" the layout using template engines
such as Velocity, Freemarker and JSP.
link:../../click-api/org/apache/click/control/Form.html#velocity-macros[Macro.vm]
is an example of a generic and reuable form layout using Velocity.

link:../../click-api/org/apache/click/control/Panel.html[Panels] provide
another good way to build generic and reusable template based layouts.

Once your generic templates are in place, they can easily be reused in
your project or even shared across multiple projects.

==== Programmatic layout

To combat the redundancy introduced by the Template approach, you can
take a programmatic approach and use normal Java and some Click classes
to build custom layouts.

Click extras provides two useful classes in this situation namely,
link:../../extras-api/org/apache/click/extras/control/HtmlForm.html[HtmlForm]
and
link:../../extras-api/org/apache/click/extras/control/HtmlFieldSet.html[HtmlFieldSet].

Unlike Form and FieldSet which renders its controls using a Table
layout, HtmlForm and HtmlFieldSet renders its controls in the order they
were added and does not add any extra markup. HtmlForm will be used in
the examples below.

To make it easy to compare the two layout approaches we will recreate
the example from the template layout section, but using the programmatic
approach.

When creating custom layouts, the HTML construct List <ul> is pretty
useful. Since Click does not provide this component, we will create it
as shown below. First we create the HTML list element <ol>, to which
list item elements <li> can be added:

[source,java]
----
// HtmlList.java
public class HtmlList extends AbstractContainer {

    public String getTag() {
        return "ol";
    }

    // Can only add ListItems: <li> tags
    public Control add(Control control) {
        if (!(control instanceof ListItem)) {
            throw new IllegalArgumentException("Only list items can be added.");
        }
        return super.add(control);
    }
}
----

Next we create the HTML list item element <li>:

[source,java]
----
// ListItem.java
public class ListItem extends AbstractContainer {

    public String getTag() {
        return "li";
    }
}
----

Another component that will be used in the example is a FieldLabel which
renders an HTML label element for a target Field.

[source,java]
----
// FieldLabel.java
public class FieldLabel extends AbstractControl {

    private Field target;

    private String label;

    public FieldLabel(Field target, String label) {
        this.target = target;
        this.label = label;
    }

    public String getTag() {
        return "label";
    }

    // Override render to produce an html label for the specified field.
    public void render(HtmlStringBuffer buffer) {
        // Open tag: <label
        buffer.elementStart(getTag());

        // Set attribute to target field's id
        setAttribute("for", target.getId());

        // Render the labels attributes
        appendAttributes(buffer);

        // Close tag: <label for="firstname">
        buffer.closeTag();

        // Add label text: <label for="firstname">Firstname:
        buffer.append(label);

        // Close tag: <label for="firstname">Firstname:</label>
        buffer.elementEnd(getTag());
    }

}
----

Now the form can be assembled. Continuing with the employee example from
the link:#template-layout[template approach], we again create an
`+EmployeePage+`, but this time an `+HtmlForm+` and `+HtmlList+` is used
to create the custom layout:

[source,java]
----
// EmployeePage.java
public class EmployeePage extends Page {
    // A form instance variable
    private HtmlForm form;

    // Build the form when the page is initialized
    public void onInit() {
        // Create an HtmlForm which is ideal for composing manual layouts
        form = new HtmlForm("form");

        // Create a list and add it to the form.
        HtmlList list = new HtmlList();
        form.add(list);

        // Add firstname field and pass in its name, label and the list to add the field to
        addTextField("firstname", "Firstname:", list);
        addTextField("lastname", "Lastname:", list);
        addTextField("age", "Age:", list);
        addTextField("salary", "Salary:", list);

        // Add a submit button to form
        form.add(new Submit("add", "Add Employee"));

        // Add the form to the page
        addControl(form);
    }

    // Provide a helper method to add fields to the form
    private void addTextField(String nameStr, String labelStr, List list) {
        // Create a new ListItem <li> and add it to the List
        ListItem item = new ListItem();
        list.add(item);

        // Create a textfield with the specified name
        Field field = new TextField(nameStr);

        // Create a field label, which associates the label with the field id.
        // label.toString would output: <label for="firstname">Firstname:</name>
        FieldLabel label = new FieldLabel(field, labelStr);

        // Next add the label and field to the list item.
        // item.toString would then produce:
        // <li>
        //   <label for="firstname">Firstname:</name>
        //   <input type="text" name="firstname" id="form_firstname" value="" size="20"/>
        // </li>
        //
        item.add(label);
        item.add(field);
    }
}
----

And lastly the `+employee.htm+` template would only need to specify the
name of the top level component, in this case `+form+`.

[source,xml]
----
<!--employee.htm-->
${form}
----

which produces the following markup:

[source,xml]
----
<form method="post" id="form" action="/myapp/employee.htm">
<input type="hidden" name="form_name" id="form_form_name" value="form"/>
    <ol>
        <li>
            <label for="firstname">Firstname:</label>
            <input type="text" name="firstname" id="form_firstname" value="" size="20"/>
        </li>
        <li>
            <label for="lastname">Lastname:</label>
            <input type="text" name="lastname" id="form_lastname" value="" size="20"/>
        </li>
        <li>
            <label for="age">Age:</label>
            <input type="text" name="age" id="form_age" value="" size="20"/>
        </li>
        <li>
            <label for="salary">Salary:</label>
            <input type="text" name="salary" id="form_salary" value="" size="20"/>
        </li>
    </ol>
    <input type="submit" name="add" id="form_add" value="Add Employee"/>
</form>
----

Again using a CSS stylesheet, the markup above can be styled and
transformed into a fancy looking form.

There is a
http://click.avoka.com/click-examples/form/contact-details.htm[live
demo] showing the programmatic approach.

The advantage of the programmatic approach is that there is no
redundancy. Each Field is created and added using normal Java. There is
no need to specify where the Field must reside in the markup.

If new requirements arrive and more fields added, only the Page needs to
change. There is no need to change the template as the layout is taken
care of by CSS and the markup produced by the components.

Disadvantages are that more upfront work is needed to write the
components and it is more difficult to _visualize_ what output would be
rendered by the components.

However once your custom layout components are in place, they can easily
be reused in your project or even shared across multiple projects.

Whether you use the link:#template-layout[template] or
link:#programmatic-layout[programmatic] layout approach, is up to you.
Both work well and have advantages and disadvantages over the other.

=== Behavior

Behaviors provide the ability to change how Controls behave at runtime.

link:../../click-api/org/apache/click/Behavior.html[Behavior] is an
interface that provides _interceptor methods_ for certain `+Control+`
life cycle events. These _interceptor methods_ can be implemented to
decorate and enhance the control and its children. This allows for
making changes to Controls such as adding/removing JavaScript and CSS
Elements, adding/removing attributes, etc.

Behaviors are added to Controls through the
link:../../click-api/org/apache/click/control/AbstractControl.html#addBehavior(org.apache.click.Behavior)[AbstractControl.addBehavior(Behavior)]
method, and the same Behavior can be shared by multiple Controls.

The `+Control+`, `+AbstractControl+` and `+Behavior+`, classes are shown
in the figure below.

Control exposes the following Behavior related methods:

* link:../../click-api/org/apache/click/Control.html#getBehaviors()[getBehaviors()]
- returns the Control's Set of Behaviors
* link:../../click-api/org/apache/click/Control.html#hasBehaviors()[hasBehaviors()]
- returns true if the Control has any Behaviors

AbstractControl contains a `+Set+` that holds the `+Behaviors+` added to
the `+Control+`. It also exposes the following methods for managing
`+Behaviors+`:

* link:../../click-api/org/apache/click/control/AbstractControl.html#addBehavior(org.apache.click.Behavior)[addBehavior(Behavior)]
- adds the given Behavior to the Control's Set of Behaviors
* link:../../click-api/org/apache/click/control/AbstractControl.html#removeBehavior(org.apache.click.Behavior)[removeBehavior(Behavior)]
- removes the given Behavior from the Control's Set of Behaviors

The Behavior interface (_interceptor methods_) is covered next:

* link:../../click-api/org/apache/click/Behavior.html#preResponse(org.apache.click.Control)[preResponse(Control)]
- defines an interceptor method that is invoked before the response is
written.
* link:../../click-api/org/apache/click/Behavior.html#preRenderHeadElements(org.apache.click.Control)[preRenderHeadElements(Control)]
- defines an interceptor method that is invoked after preResponse() but
before the `+Control+` getHeadElements() is called. This is a good place
to add custom JavaScript or CSS elements to Controls.
* link:../../click-api/org/apache/click/Behavior.html#preDestroy(org.apache.click.Control)[preDestroy()]
- defines an interceptor method that is invoked before the `+Control+`
onDestroy() event handler. This interceptor method allows the behavior
to cleanup any resources.

==== Behavior Execution

When a Behavior is added to a Control, the Control is automatically
registered with the
link:../../click-api/org/apache/click/ControlRegistry.html[ControlRegistry].
Registering with the ControlRegistry allows the Click runtime to quickly
and easily access controls that have Behaviors and process them.
Controls without behaviors won't be registered and won't be processed.

Click will invoke all the registered Behavior's _interceptor methods_ at
the appropriate time during the `+Control+` life cycle.

==== Behavior Example

Let's look at a simple Behavior example. Say we want to put focus on a
Field in our Form. Normally we would use the following JavaScript
snippet somewhere in our page template:

[source,javascript]
----
        document.getElementById('form_nameField').focus();
----

If we want this behavior on another page we can copy and paste this
snippet to the other page template and update the field ID.
Alternatively we can create a custom `+FocusBehavior+` that adds the
necessary JavaScript to a target Field:

[source,java]
----
    public class FocusBehavior implements Behavior {

        public void preRenderHeadElements(Control control) {
            String id = control.getId();
            JsScript jsScript = new JsScript("document.getElementById('" + id + "').focus();");

            // Set script to execute as soon as browser dom is ready. NOTE: The
            // JavaScript logic determining when the DOM is ready is added by
            // the Form control, through the script '/click/control.js'.
            script.setExecuteOnDomReady(true);

            // Add the JavaScript element to the Control
            control.getHeadElements().add(jsScript);
        }

        ...
    } 
----

Below is an example using the `+FocusBehavior+`:

[source,java]
----
    public class MyPage extends Page {

    private Form form = new Form("form");
    private TextField nameField = new TextField("nameField");

        public MyPage() {
            addControl(form);
            form.add(nameField);

            // Create the custom behavior
            FocusBehavior focus = new FocusBehavior();

            // Add the behavior to the field
            nameField.addBehavior(focus);
        }
    } 
----

At runtime the _nameField_ will be registered with the
`+ControlRegistry+` when the `+FocusBehavior+` is added to the field.

Before the Control's HEAD elements are rendered, Click will invoke the
`+FocusBehavior+` _interceptor method_,
link:../../click-api/org/apache/click/Behavior.html#preRenderHeadElements(org.apache.click.Control)[preRenderHeadElements(Control)],
passing the _nameField_ as an argument.

The FocusBehavior preRenderHeadElements method will add the JavaScript
code to the Field HEAD elements which will be rendered as part of the
server response.

Our JavaScript snippet is executed by the browser as soon as the DOM is
ready, in other words _after_ our nameField has been rendered. Focus
will be set on the _nameField_.
