# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Checkstyle CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Step 3: Executa o check e gera o relatório simultaneamente
    # O comando 'validate' dispara o 'check' (conforme seu POM)
    # O 'site' gera os relatórios HTML
    - name: Run Checkstyle and Generate Report
      run: mvn validate checkstyle:checkstyle -DskipTests

    # Step 4: Upload de todos os relatórios (usa wildcard para pegar de todos os módulos)
    - name: Upload Checkstyle Report
      if: always() # Garante o upload mesmo se o build falhar por violações
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-reports
        path: "**/target/site/checkstyle.html"
        retention-days: 15
